# Generated by Django 2.2.2 on 2019-06-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('name_game', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=120)),
                ('game_time', models.DateField()),
                ('position', models.CharField(max_length=4)),
                ('time', models.PositiveSmallIntegerField()),
                ('two_hit', models.PositiveSmallIntegerField()),
                ('two_shot', models.PositiveSmallIntegerField()),
                ('three_hit', models.PositiveSmallIntegerField()),
                ('three_shot', models.PositiveSmallIntegerField()),
                ('penalty_hit', models.PositiveSmallIntegerField()),
                ('penalty_shot', models.PositiveSmallIntegerField()),
                ('front', models.PositiveSmallIntegerField()),
                ('back', models.PositiveSmallIntegerField()),
                ('bord', models.PositiveSmallIntegerField()),
                ('sup', models.PositiveSmallIntegerField()),
                ('foul', models.PositiveSmallIntegerField()),
                ('ST', models.PositiveSmallIntegerField()),
                ('miss', models.PositiveSmallIntegerField()),
                ('block', models.PositiveSmallIntegerField()),
                ('point', models.PositiveSmallIntegerField()),
                ('ZF', models.SmallIntegerField()),
                ('first', models.PositiveSmallIntegerField()),
                ('team_name', models.CharField(max_length=120)),
                ('HA', models.SmallIntegerField()),
                ('A_point', models.SmallIntegerField()),
                ('H_point', models.SmallIntegerField()),
                ('two_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('three_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('penalty_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('wining', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'black',
                'verbose_name_plural': 'blacks',
                'db_table': 'playerinfo',
                'managed': True,
            },
        ),
    ]
